# 1. Load and Preprocess Data


Here is where we are going to prepare the dataset for training our machine learning models.

Let's load the data into a Pandas DataFrame. Each row represents a sample (client), and each column represents a feature (such as number of children, annual income, income category) or the label (Outcome).

We will also check and remove duplicates. Duplicate rows can bias the model, so it's important we remove them.

Check and clean rows with NULL entries. Missing values can prevent the model from training.

In [58]:
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("samuelcortinhas/credit-card-approval-clean-data")

print("Path to dataset files:", path)

df_application = pd.read_csv(os.path.join(path, 'clean_dataset.csv'))

Path to dataset files: /Users/henrywei/.cache/kagglehub/datasets/samuelcortinhas/credit-card-approval-clean-data/versions/2

## 1.1 Investigate the dataset
We checked the dataset by using head method and info method.

As the results presented, there are 16 columns, most of which are numerical variables. Only industry, citizen, and ethnicity columns are categorical variables. To train the model, we need to process these data.

In [59]:
df_application.head(20)

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.250,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.040,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.500,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.750,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.710,1,0,0,0,ByOtherMeans,120,0,1
5,1,32.08,4.000,1,1,CommunicationServices,White,2.500,1,0,0,1,ByBirth,360,0,1
6,1,33.17,1.040,1,1,Transport,Black,6.500,1,0,0,1,ByBirth,164,31285,1
7,0,22.92,11.585,1,1,InformationTechnology,White,0.040,1,0,0,0,ByBirth,80,1349,1
8,1,54.42,0.500,0,0,Financials,Black,3.960,1,0,0,0,ByBirth,180,314,1
9,1,42.50,4.915,0,0,Industrials,White,3.165,1,0,0,1,ByBirth,52,1442,1
10,1,22.08,0.830,1,1,Energy,Black,2.165,0,0,0,1,ByBirth,128,0,1
11,1,29.92,1.835,1,1,Energy,Black,4.335,1,0,0,0,ByBirth,260,200,1
12,0,38.25,6.000,1,1,Financials,White,1.000,1,0,0,1,ByBirth,0,0,1
13,1,48.08,6.040,1,1,Financials,White,0.040,0,0,0,0,ByBirth,0,2690,1
14,0,45.83,10.500,1,1,Materials,White,5.000,1,1,7,1,ByBirth,0,0,1
15,1,36.67,4.415,0,0,Financials,White,0.250,1,1,10,1,ByBirth,320,0,1
16,1,28.25,0.875,1,1,CommunicationServices,White,0.960,1,1,3,1,ByBirth,396,0,1
17,0,23.25,5.875,1,1,Materials,White,3.170,1,1,10,0,ByBirth,120,245,1
18,1,21.83,0.250,1,1,Real Estate,Black,0.665,1,0,0,1,ByBirth,0,0,1
19,0,19.17,8.585,1,1,InformationTechnology,Black,0.750,1,1,7,0,ByBirth,96,0,1

In [60]:
df_application.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    object
 6   Ethnicity       690 non-null    object
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    object
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), object(3)
memory usage: 86.4+ KB

#  2. Feature Engineering
We convert the categorical variables into numbers for machine learning by using one-hot encoding and ordinal encoding based on the nature of the data type.

The program transform the feature columns needed for modeling. 

* concat method combines two or more dataframe together
* get dummies executes one-hot encoding by converting categorical columns into multiple  0/1 columns

In [61]:
def features(df):
    X = df[['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'YearsEmployed', 'PriorDefault', 'Employed', 'CreditScore', 'DriversLicense', 'Income']].copy()
    X = pd.concat([X, pd.get_dummies(df['Industry'], prefix='Industry')], axis=1)
    X = pd.concat([X, pd.get_dummies(df['Ethnicity'], prefix='Ethnicity')], axis=1)
    citizen_groups = {
        'ByBirth': 2,
        'ByOtherMeans': 1,
        'Temporary': 0         
    }

    X["Citizen_number"] = [citizen_groups[x] for x in df["Citizen"]]
    return X
clean_data = features(df_application)
clean_data.head(20)

,Gender,Age,Debt,Married,BankCustomer,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,...,Industry_Real Estate,Industry_Research,Industry_Transport,Industry_Utilities,Ethnicity_Asian,Ethnicity_Black,Ethnicity_Latino,Ethnicity_Other,Ethnicity_White,Citizen_number
0,1,30.83,0.000,1,1,1.250,1,1,1,0,...,False,False,False,False,False,False,False,False,True,2
1,0,58.67,4.460,1,1,3.040,1,1,6,0,...,False,False,False,False,False,True,False,False,False,2
2,0,24.50,0.500,1,1,1.500,1,0,0,0,...,False,False,False,False,False,True,False,False,False,2
3,1,27.83,1.540,1,1,3.750,1,1,5,1,...,False,False,False,False,False,False,False,False,True,2
4,1,20.17,5.625,1,1,1.710,1,0,0,0,...,False,False,False,False,False,False,False,False,True,1
5,1,32.08,4.000,1,1,2.500,1,0,0,1,...,False,False,False,False,False,False,False,False,True,2
6,1,33.17,1.040,1,1,6.500,1,0,0,1,...,False,False,True,False,False,True,False,False,False,2
7,0,22.92,11.585,1,1,0.040,1,0,0,0,...,False,False,False,False,False,False,False,False,True,2
8,1,54.42,0.500,0,0,3.960,1,0,0,0,...,False,False,False,False,False,True,False,False,False,2
9,1,42.50,4.915,0,0,3.165,1,0,0,1,...,False,False,False,False,False,False,False,False,True,2
10,1,22.08,0.830,1,1,2.165,0,0,0,1,...,False,False,False,False,False,True,False,False,False,2
11,1,29.92,1.835,1,1,4.335,1,0,0,0,...,False,False,False,False,False,True,False,False,False,2
12,0,38.25,6.000,1,1,1.000,1,0,0,1,...,False,False,False,False,False,False,False,False,True,2
13,1,48.08,6.040,1,1,0.040,0,0,0,0,...,False,False,False,False,False,False,False,False,True,2
14,0,45.83,10.500,1,1,5.000,1,1,7,1,...,False,False,False,False,False,False,False,False,True,2
15,1,36.67,4.415,0,0,0.250,1,1,10,1,...,False,False,False,False,False,False,False,False,True,2
16,1,28.25,0.875,1,1,0.960,1,1,3,1,...,False,False,False,False,False,False,False,False,True,2
17,0,23.25,5.875,1,1,3.170,1,1,10,0,...,False,False,False,False,False,False,False,False,True,2
18,1,21.83,0.250,1,1,0.665,1,0,0,1,...,True,False,False,False,False,True,False,False,False,2
19,0,19.17,8.585,1,1,0.750,1,1,7,0,...,False,False,False,False,False,True,False,False,False,2

## 2.1 Clean dataset

After processing the dataset, we stored it in clean_data and check the data type of each column using info method

In [62]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          690 non-null    int64
 1   Age                             690 non-null    float64
 2   Debt                            690 non-null    float64
 3   Married                         690 non-null    int64
 4   BankCustomer                    690 non-null    int64
 5   YearsEmployed                   690 non-null    float64
 6   PriorDefault                    690 non-null    int64
 7   Employed                        690 non-null    int64
 8   CreditScore                     690 non-null    int64
 9   DriversLicense                  690 non-null    int64
 10  Income                          690 non-null    int64
 11  Industry_CommunicationServices  690 non-null    bool
 12  Industry_ConsumerDiscretionary  690 non-null    bool
 13  Industry_ConsumerStaples        690 non-null    bool
 14  Industry_Education              690 non-null    bool
 15  Industry_Energy                 690 non-null    bool
 16  Industry_Financials             690 non-null    bool
 17  Industry_Healthcare             690 non-null    bool
 18  Industry_Industrials            690 non-null    bool
 19  Industry_InformationTechnology  690 non-null    bool
 20  Industry_Materials              690 non-null    bool
 21  Industry_Real Estate            690 non-null    bool
 22  Industry_Research               690 non-null    bool
 23  Industry_Transport              690 non-null    bool
 24  Industry_Utilities              690 non-null    bool
 25  Ethnicity_Asian                 690 non-null    bool
 26  Ethnicity_Black                 690 non-null    bool
 27  Ethnicity_Latino                690 non-null    bool
 28  Ethnicity_Other                 690 non-null    bool
 29  Ethnicity_White                 690 non-null    bool
 30  Citizen_number                  690 non-null    int64
dtypes: bool(19), float64(3), int64(9)
memory usage: 77.6 KB

## 2.2 Target Column
We stored the target column as y dataset

In [63]:
y = df_application['Approved'].copy()

# 3. Train the model
In this project, we planned to train the dataset using different approach and comparing which method has the best accuracy rate.

* Logistic Regression: Predict the probability using a logistic function on a linear combination of features
* K-Neighbors Classifier: Classify based on the majority of its k nearest neighbors 
* MLP Classifier: Using multi layer of neurons to make a prediction

## 3.1 Split the dataset into testing data and training data
Train_test_split from the sklearn library was used to split the data into training and testing sets, with 80% for training and 20% for testing.

Notice that random_state parameter is set to 42, which ensures that reruning the code will consistently produce the same split, making the results reproducible.

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(clean_data, y, test_size = 0.2, random_state = 42)

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

## 3.2 Standardize features
Columns like ages, YearsEmployed, and income might have a significant different range. 
Standardizing these columns ensure that each variable equally impact the prediction

* fit_transform: applied to the training set to compute the mean and standard deviation

* transform: applied to the testing set using the same parameters

In [66]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

###  3.3 Logistic Regression

In [67]:
# Logistic Regression
lrmodel = LogisticRegression()
lrmodel.fit(X_train_scaled, y_train)

y_pred = lrmodel.predict(X_test_scaled)
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.8260869565217391
              precision    recall  f1-score   support

           0       0.81      0.84      0.83        68
           1       0.84      0.81      0.83        70

    accuracy                           0.83       138
   macro avg       0.83      0.83      0.83       138
weighted avg       0.83      0.83      0.83       138

### 3.4 K-Neighbors Classifier
We used the nearest 5 neighbors for prediction

In [68]:
from sklearn.neighbors import KNeighborsClassifier
model_K = KNeighborsClassifier(n_neighbors=5)
model_K.fit(X_train_scaled, y_train)
y_pred =model_K.predict(X_test_scaled)
print(f"KNeighbors Classifier Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))

KNeighbors Classifier Accuracy: 0.7463768115942029
              precision    recall  f1-score   support

           0       0.71      0.82      0.76        68
           1       0.80      0.67      0.73        70

    accuracy                           0.75       138
   macro avg       0.75      0.75      0.75       138
weighted avg       0.75      0.75      0.75       138

###  3.5 MLP Classifier
* solver: 'lbfgs' a quasi-Newton method used to optimize the network's weights during training, preform better on small data
* alpha: prevent overfitting
* hidden_layer_sizes: We tried several combination, including (32, 16, 8), (16,8), (8,4). (8,2) preforms the best
* random_state: 11, ensures reproducible results
* max_iter: maximum numbers of iteration

In [69]:
from sklearn.neural_network import MLPClassifier
mlp_classifier = MLPClassifier(solver='lbfgs', alpha=1e-5,
                               hidden_layer_sizes=(8,2), random_state=11,max_iter=10000)
mlp_classifier.fit(X_train_scaled, y_train)
y_pred = mlp_classifier.predict(X_test_scaled)
print(f"MLP Classifier Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))

MLP Classifier Accuracy: 0.8188405797101449
              precision    recall  f1-score   support

           0       0.79      0.87      0.83        68
           1       0.86      0.77      0.81        70

    accuracy                           0.82       138
   macro avg       0.82      0.82      0.82       138
weighted avg       0.82      0.82      0.82       138

# 4. Evaluation
Out of the three methods, MLP and logistic regression have a similar accuracy rate of 0.83. K-neighbors approach preformed poorly with a roughly 0.75 accuracy rate. Investigating deeper in the metrics, we can see that MLP has a higher precision score of 0.86 and a lower recall score of 0.79. On the other hand, logistic regression has a similar precision score and recall score of 0.84 and 0.81 respectively. 

From a customer's perspective, recall is extremely important, as being rejected for a credit card can be harmful and frustrating. A model with higher recall reduces the chance of wrongly denying eligible applicants. Because logistic regression has the highest recall among the competitive models, it would be the most customer-friendly choice.

In [70]:
try:
    import lime
except:
    !pip install lime
    import lime

In [92]:
print(X_train.columns)

Index(['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'YearsEmployed',
       'PriorDefault', 'Employed', 'CreditScore', 'DriversLicense', 'Income',
       'Industry_CommunicationServices', 'Industry_ConsumerDiscretionary',
       'Industry_ConsumerStaples', 'Industry_Education', 'Industry_Energy',
       'Industry_Financials', 'Industry_Healthcare', 'Industry_Industrials',
       'Industry_InformationTechnology', 'Industry_Materials',
       'Industry_Real Estate', 'Industry_Research', 'Industry_Transport',
       'Industry_Utilities', 'Ethnicity_Asian', 'Ethnicity_Black',
       'Ethnicity_Latino', 'Ethnicity_Other', 'Ethnicity_White',
       'Citizen_number'],
      dtype='object')

In [90]:
import numpy

Gender = 0
Age = 19
Debt = 0
Married = 0
BankCustomer = 1
YearsEmployed = 0.05
PriorDefault = 0
Employed = 1
CreditScore = 5
DriversLicense = 1
Income = 300
Industry_CommunicationServices =0
Industry_ConsumerDiscretionary =0
Industry_ConsumerStaples =0
Industry_Education = 0
Industry_Energy = 0
Industry_Financials = 0
Industry_Healthcare = 0
Industry_Industrials = 0
Industry_InformationTechnology = 1
Industry_Materials = 0
Industry_Real_Estate = 0
Industry_Research = 0 
Industry_Transport = 0
Industry_Utilities = 0
Ethnicity_Asian = 1
Ethnicity_Black = 0
Ethnicity_Latino = 0
Ethnicity_Other = 0
Ethnicity_White = 0
Citizen_number = 2

input_data =numpy.array([[Gender, Age, Debt, Married, BankCustomer, YearsEmployed,
       PriorDefault, Employed, CreditScore, DriversLicense, Income,
       Industry_CommunicationServices, Industry_ConsumerDiscretionary,
       Industry_ConsumerStaples, Industry_Education, Industry_Energy,
       Industry_Financials, Industry_Healthcare, Industry_Industrials,
       Industry_InformationTechnology, Industry_Materials,
       Industry_Real_Estate, Industry_Research, Industry_Transport,
       Industry_Utilities, Ethnicity_Asian, Ethnicity_Black,
       Ethnicity_Latino, Ethnicity_Other, Ethnicity_White,
       Citizen_number]])

input_scaled = scaler.transform(input_data)
print(input_scaled)

# Predict
y_predicted_lr = lrmodel.predict(input_scaled)
score = lrmodel.predict_proba(input_scaled)

if y_predicted_lr[0] == 1:
    print(f"The person is likely to get accepted (classifier confidence = {score[0][1]:.4f})")
else:
    print(f"The person will get rejected (classifier confidence = {score[0][0]:.4f})")

[[-1.53148769 -1.05683774 -0.9586808  -1.74045887  0.57177187 -0.68411692
  -1.02569226  1.15287203  0.53612959  1.09909053 -0.12964143 -0.24806947
  -0.3086067  -0.29065335 -0.19886685 -0.52143015 -0.2979218  -0.28325754
  -0.34594141  4.24670257 -0.35247163 -0.20373864 -0.11333153 -0.06030227
  -0.21320072  3.31662479 -0.49603393 -0.29430286 -0.20851441 -1.21921552
   0.29614086]]
The person will get rejected (classifier confidence = 0.8068)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [87]:
from lime import lime_tabular


explainer = lime_tabular.LimeTabularExplainer(
    training_data=X_train.to_numpy(),
    feature_names=X_train.columns,
    class_names=[0, 1],
    mode='classification'
)

In [89]:
exp = explainer.explain_instance(
    data_row=input_scaled,
    predict_fn=lrmodel.predict_proba
)

exp.show_in_notebook(show_table=True)

ValueError: could not broadcast input array from shape (31,) into shape (1,)